MAIN:
  # MANGE
  AREA_DETECTION: [125, 140, 960, 530]
  TIME_TO_GET_DATA: 1 # minute
  SAVE_CSV: True
  HEADER_CSV: ['time_current (dd/mm/YY H:M:S)', 'time_process', 'fps_process_average (frame/second)', 'speed_flow (km/hr)', 'count_vehicle', 'count_accident', 'count_vehicle_all']
  USE_SOCKET: False
  SOCKET_ID_NAME: 2
  USE_INFLUXDB: True
  INFLUXDE_MEASURE_NAME: 'place2'
  INFLUXDB_HOST_IP: '192.168.96.1'
  INFLUXDB_PORT: 8086
  INFLUXDB_USERNAME: 'grafana'
  INFLUXDB_PASSWORD: 'password01'
  INFLUXDB_DATABASE: 'TrafficAnalysis'

  # YOLOv5 check all class detected in yolov5/data/coco.yaml
  PATH_WEIGHT_YOLOV5: 'object_detection/yolov5/weights/yolov5m.pt'
  CONFIDENCE_THRESHOLD: 0.5
  CLASSES: [2, 3, 5, 6, 7, 8] # [2(car), 3(motorcycle), 5(bus), 6(train), 8(truck)]
  SHOW_VID: True
  WEBCAM: False
  SAVE_VID: False
  VISUALIZE: False
  # PATH_SOURCE: 'videos/t3.mp4'
  PATH_SOURCE: 'https://sn.rtsp.me/A0dxD1cYX-T7XdVy--UJ0Q/1648189089/hls/57s5ddDs.m3u8'
  PATH_SAVE: 'inference/outputs/final-02.mp4'
  PATH_SAVE_CSV: 'inference/outputs/final-02.csv'

  # OBJECT TRACKING
  LIMIT_DISTANCE: 50
  MIN_DISTANCE_UPDATE: 10

  # VEHECLE COUNTING
  FRAME_TO_COUNT: 10

  # COUNT_LINE: [
  #   [[10, 250], [600, 140]],
  #   [[10, 400], [700, 200]]
  #   # [[20, 30], [200, 30]]
  # ]

  COUNT_AREA: [
    [[0, 200], [430, 180], [820, 250], [20, 380]],
    # [[0, 0], [200, 0], [200, 500], [0, 500]],
  ]
  FRAME_BUFFER: 5 # frame
  MAX_AGE: 60

  # SPEED ESTIMATION
  FRAME_TO_CALCULATE_SPEED: 8 # frame
  TRACKING_LIMIT_DISTANCE: 50 # pixel
  # km/h mode
  SPEED_OUT_OF_SIGHT: 30 # km/h
  SPEED_OUT_OF_SIGHT_CAR_STOP: 9 # km/h
  # pixel/h mode
  # SPEED_OUT_OF_SIGHT: 1230 # kpixel/h
  # SPEED_OUT_OF_SIGHT_CAR_STOP: 369 # kpixel/h

  METERS_PER_PIXELS: 0.012
  FRAME_RATE_SOURCE: 30


  # ACCIDENT DETECTION
  AREA_ACCIDENT_CHECK: [
    [[0, 0], [960, 0], [960, 530], [0, 530]],
    # [[100, 50], [300, 50], [300, 100], [100, 100]],
  ]
  LIMIT_TIME: 1 # minute
  MIN_SPEED_TO_CHECK_COUNT_ACCIDENT: 3 # km/hr
  # MIN_SPEED_TO_CHECK_COUNT_ACCIDENT: 123 # kpixels/hr


## TRACKING PARAMETERS
    # list parameter definition
    # tracking_list_obj = [
    #     (obj_center_x, obj_center_y), 
    #     life for delete tracking, 
    #     flag for decrease life, 
    #     number for count car,
    #     (number for start calculate speed, distance stack, speed is pixels(or kilimeters) per hours)
    #     [[center_buffer]],
    #     limit_number,
    #     flag_count,
    #     count_check_accident
    #     flag_accident
    # ] 

  